### ISSUE TITLE
Label filter not working

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#11]
The selection criteria for Label_1 is default set to "Monoculture", but all three categories pop up in the display box--even though only the data from Label_1 are displayed.

**Comment by nathanhwangbo** [comment]
Can you explain this issue a bit more? It looks like our code is ignoring the `selected` argument because `summary_all$Legend_1` does not have a value of `Monoculture` anywhere. (I'm assuming Legend_1 is what you intended by Label_1, but let me know if I'm mistaken!)
