### ISSUE TITLE
Split out UI and server into separate R files

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#14]

**Comment by nathanhwangbo** [comment]
I put the split script files (called `server.R` and `ui.R`) into a folder inside `www` called `appScripts`.  
We can run the app from either of the scripts using the "Run App" button, or run the app from anywhere using the following command: `runApp(<path from working directory>/appScripts")`.

I also deleted the original `app.R` file to hopefully avoid confusion.

**Comment by swood-ecology** [comment]
This generated a bunch of new errors for me:
```Warning: Error in eval: object 'summary_all' not found
  106: eval
  105: eval
  104: %>%
  103: eventReactiveHandler [/Users/stephen.wood/Box Sync/Work/Code/Midwest-Agriculture-Synthesis/www/appScripts/server.R#21]
   59: df0
   58: observeEventExpr
    1: runApp
Warning: Error in eval: object 'summary_all' not found
  106: eval
  105: eval
  104: %>%
  103: eventReactiveHandler [/Users/stephen.wood/Box Sync/Work/Code/Midwest-Agriculture-Synthesis/www/appScripts/server.R#21]
   59: df0
   58: observeEventExpr
    1: runApp
```

Are you getting those as well?
