### ISSUE TITLE
Add control description to x-axis

### ISSUE THREAD

**Issue by LesleyAtwood** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#19]
Each review has a different experimental control, which can be displayed on the x-axis at 0.  Either as a replacement for 0 or below 0...depends on readability. The controls are as followed:

Review Name, Control Description
Cover Crops, No Cover Crops
Early Season Pest Management, No Pesticides
Fertilizer Application (Split), Single Application
Fert App (Variable Rate), Uniform Application
Fert Placement (Banding), Broadcast Application
Fert Placement (Subsurface), Applied to Surface
Fertilizer Timing (Fall & Spring),  Applied in Fall
Fertilizer Timing (Pre/Post Planting), Applied Preplant

**Comment by nathanhwangbo** [comment]
Added these underneath the 0 point

**Comment by LesleyAtwood** [comment]
Awesome. 

I noticed that if the user selects two inputs for Outcome [e.g. Soil and Crop Production] then two control descriptions are printed on top of one another. Can we make it so only one appears regardless of the number of Outcomes the user selects? The printed text is the same since the user can only select one Management Practice at a time.

**Comment by nathanhwangbo** [comment]
This should be fixed in the latest commit!
