### ISSUE TITLE
Error on master branch

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#37]
I just pulled the recent update to the master branch to Cosima and it now generates an error: http://cosima.nceas.ucsb.edu/ag-evidence/

It seems like a few things were updated. @nathanhwangbo @brunj7 Can you have a look and see what might have caused the problem?

**Comment by nathanhwangbo** [comment]
Can you tell me where the error showed up? I'm clicking through a few options in the app, but I can't seem to generate an error.

It might be the addition of new packages `RColorBrewer`, `grid`, and `cowplot`. Maybe they need to be installed?

Other than that, it might have to do with a small change I made in how we read in `summary_all`, which can be found in the file `global.R`. I implemented this change from a code snippet you and Lesley provided in #35, but using the `here` function. However, this code uses the same root as the old version, so it doesn't seem like this would be our problem.

**Comment by swood-ecology** [comment]
@brunj7 fixed this yesterday. sorry I didn't close this then.
