### ISSUE TITLE
New References Alert!

### ISSUE THREAD

**Issue by shiny-som** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#39]
Hello! 
 

There are at least 157 new papers for the Midwest Agriculture Reviews! This alert is counting papers from 2019-10-11 to 2019-10-11.
-------------
The API returns: 

Cover crops > 47
Nutrient Management > 56
Pest Management > 10
Tillage > 44
-------------
The queries used to generate these numbers are below:

Cover crops: "cover crop" OR cover-crop* OR covercrop*

Nutrient Management: (precision AND (fert* OR agr* OR nitrogen OR phosphorous)) OR "variable rate" OR "band* fert*" OR 4R OR ((enhance* OR efficien*) AND (nitrogen OR phosphorous)) 

Pest Management: "pesticide seed treatment"* OR "seed treatment*" OR "systemic insect*" OR neonic* OR pyrethr* OR (foliar AND insecticide*)

Tillage: "conservation till*" OR "conventional till" OR "no-till" OR "no till*" OR "reduced till*" OR "minimum till*" 

------------- 

The 
Happy reviewing!
(this email was generated at 2019-10-11 12:31:59)

**Comment by swood-ecology** [comment]
@nathanhwangbo this is really cool! is this set to run from now on?

also, it says that the search only counts papers for 1 day. that seems like an error? "This alert is counting papers from 2019-10-11 to 2019-10-11"

when I used these search terms in Web of Science to search from 2017 to present I was getting much different number of results, like more than twice as much. Here's an example of cover crops.

[cc-midwest-2019_10.txt](https://github.com/Science-for-Nature-and-People/Midwest-Agriculture-Synthesis/files/3719471/cc-midwest-2019_10.txt)

**Comment by swood-ecology** [comment]
@nathanhwangbo also, it says that the search only counts papers for 1 day. that seems like an error? "This alert is counting papers from 2019-10-11 to 2019-10-11"

**Comment by nathanhwangbo** [comment]
There are still a few kinks to iron out, so it's not quite ready to be automated. The info in the message above is all dummy info that I put in to make sure the alert was triggered. Sorry about the confusion!

I'm trying to see if I can get the GitHub API to assign you guys to the issue so making a new issue will send out emails.

Would you rather have the bot keep commenting on 1 issue, or have it make a new issue every time the alert is triggered?

**Comment by swood-ecology** [comment]
Ah ok. It did send out an email to me, so that seems to work! 

I think having the bot comment on one issue is cleaner. Happy to close this if you think we're good on this now.
