### ISSUE TITLE
Add download link for full data set(s)

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#7]
Add a link to download all of the data associated with the given selection.

**Comment by nathanhwangbo** [comment]
Added a download button to the bottom of the page. This takes the data from `df2()` (all the currently filtered observations) and writes it to csv.

This was done by adding `output$downloadData` and `downloadButton` to `server.R` and `ui.R` respectively. 
It currently names the file "app_data.csv", but that is easily changed through the `filename` argument in the `downloadHandler` function.

**Comment by swood-ecology** [comment]
The download button should specify that it's to download data. Can the download data (and download figure) buttons go next to the update button?
