### ISSUE TITLE
Add a reference list for papers included

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/Midwest-Agriculture-Synthesis#8]
For all of the papers in the given selection, add a list of references on the main page, below the mad lib text area. This should be formatted as:

AuthorLast AuthorFirstInitial et al. Year. Title. Journal. Issue. doi.

**Comment by LesleyAtwood** [comment]
Reference table is now available for all reviews. It is available in the www/data folder
references-for-app.csv
